services:
  - type: web
    name: shi-storage
    runtime: docker
    repo: https://github.com/shishiawase/teldrive.git
    plan: free
    envVars:
      - fromGroup: teldrive-env

envVarGroups:
  - name: teldrive-env
    envVars:
      - key: PORT
        value: 8080
