services:
  - type: web
    name: shitel
    runtime: image
    image:
      url: ghcr.io/divyam234/teldrive/server
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - fromGroup: teldrive-env
