services:
  - type: web
    name: shi-storage
    runtime: image
    image:
      url: ghcr.io/divyam234/teldrive/server:latest
    plan: free
    envVars:
      - fromGroup: teldrive-env

envVarGroups:
  - name: teldrive-env
    envVars:
      - key: PORT
        sync: false
